package treesitter;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TSWasmError extends Structure {
	/**
	 * @see TSWasmErrorKind<br>
	 * C type : TSWasmErrorKind
	 */
	public int kind;
	/** C type : char* */
	public Pointer message;
	public TSWasmError() {
		super();
	}
	protected List<String> getFieldOrder(){
		return Arrays.asList("kind", "message");
	}
	/**
	 * @param kind @see TSWasmErrorKind<br>
	 * C type : TSWasmErrorKind<br>
	 * @param message C type : char*
	 */
	public TSWasmError(int kind, Pointer message) {
		super();
		this.kind = kind;
		this.message = message;
	}
	public static class ByReference extends TSWasmError implements Structure.ByReference {
		
	};
	public static class ByValue extends TSWasmError implements Structure.ByValue {
		
	};
}
